source:
  database:
    host: chinook
    db_type: sqlite
  table:
    - albums
    - artists
    - customers
    - employees
    - genres
    - invoice_items
    - invoices
    - media_types
    - playlist_track
    - playlists
    - tracks
    